### PR TITLE
Amend: Added a check publication state

### PR DESCRIPTION
**Pull request by Jake-Nichols-Soak**
From here: https://github.com/MattieBelt/mattie-strapi-bundle/pull/109

### CODE REVIEW

**Review by russell-wilson-soak — APPROVED** [review]

**Comment by james-soak** [comment]
Can I check what the plan with this is? Why not store it locally in the project and symlink it?

**Comment by james-soak** [comment]
Because you won't just be able to pull it down via NPM from a private repo - and this repo is now public?

**Review by james-soak — CHANGES_REQUESTED** [review]
Would prefer this repo removed and files are managed in the AST repo.

**Comment by Jake-Nichols-Soak** [comment]
@james-soak My plan is to have this locally within the project, but I wanted a copy on git regardless and yes I can't make forked projects private due to "security reasons"

**Pull request closed without merging**
